# Generated by Django 4.2.6 on 2023-11-03 03:27

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Anonymous', max_length=15, verbose_name='Name')),
                ('body', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Body')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created DateTime')),
                ('likes', models.PositiveIntegerField(blank=True, default=0, verbose_name='likes')),
                ('pictures', cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='pictures')),
            ],
            options={
                'db_table': 'post',
            },
        ),
    ]
